# docker-compose run autobdd-run "--project ${BDD_PROJECT}"
# 
version: '3.5'
services:
  autobdd-dev:
    build:
      context: ~/Projects/AutoBDD
      dockerfile: docker/autobdd-dev.dockerfile
      args:
        AutoBDD_Ver: ${AutoBDD_Ver}
    image: "xyteam/autobdd-dev:${AutoBDD_Ver}"
    container_name: autobdd-dev
    shm_size: 1536M
    user: root
    privileged: true
    volumes:
      - ${HOME}/.ssh:/home/${USER}/.ssh:rw
      - ${HOME}/.m2:/home/${USER}/.m2:rw
      - ${HOME}/Projects:/home/${USER}/Projects:rw
    ports:
      - "5911:5900"
      - "2211:22"
    environment:
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      VNC_PASSWORD: ${VNC_PASSWORD}
      RESOLUTION: 1920x1200x24
    entrypoint: "/autobdd-dev.startup.sh"

  autobdd-run:
    build:
      context: ~/Projects/AutoBDD
      dockerfile: docker/autobdd-run.dockerfile
      shm_size: 128M
      args:
        AutoBDD_Ver: ${AutoBDD_Ver}
    image: "xyteam/autobdd-run:${AutoBDD_Ver}"
    container_name: autobdd-run
    shm_size: 1536M
    user: root
    privileged: true
    volumes:
      - ${HOME}/.m2:/home/${USER}/.m2:rw
    environment:
      USER: ${USER}
    entrypoint: "/autobdd-run.startup.sh"
