# docker-compose run autobdd-run "--project ${BDD_PROJECT}"
# 
version: '3.5'
services:
  autobdd-dev:
    image: "xyteam/autobdd-dev:1.0.2"
    container_name: autobdd-dev
    build:
      context: .
      shm_size: 2G
    user: root
    privileged: true
    volumes:
      - ${HOME}/.ssh:/home/${USER}/.ssh:rw
      - ${HOME}/.m2:/home/${USER}/.m2:rw
      - ${HOME}/Projects:/home/${USER}/Projects:rw
    ports:
      - "5901:5900"
      - "2222:22"
    environment:
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      VNC_PASSWORD: ${VNC_PASSWORD}
      RESOLUTION: 1920x1200
    entrypoint: "/startup.sh"

  autobdd-run:
    image: "xyteam/autobdd-run:1.0.2"
    container_name: autobdd-run
    build:
      context: .
      shm_size: 2G
    user: root
    privileged: true
    volumes:
      - ${HOME}/.m2:/home/${USER}/.m2:rw
      - ${HOME}/Projects/${BDD_PROJECT}:/home/${USER}/Projects/AutoBDD/test-projects/${BDD_PROJECT}
    environment:
      USER: ${USER}
    entrypoint: "/startup.sh"
